// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nklkvvaegxqecbmbljns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rbGt2dmFlZ3hxZWNibWJsam5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTUxOTcsImV4cCI6MjA2NzE3MTE5N30.PnvUtD9_f5vPqzJPc3SAclwRsieY_fxa5MfIIMPG9zg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});